### ISSUE TITLE
Update and extend documentation for crate exported structures and Readme

### ISSUE THREAD

**Issue by CPerezz** [ZK-Garage/plonk#11]

**Comment by markulf** [comment]
Document need for Nightly
`rustup override set nightly`

Added a rust-toolchain file that forces you to use nightly directly.

**Comment by markulf** [comment]
Where will documentation pags go? https://docs.rs/ark-plonk/ is currently broken. Note that crate names need to be globally unique to run `cargo publish`.

They will go to the name that appears on the `Cargo.toml`. Anyway this will happen once we publish.

Also, for what it refers to the broken link. I'm trying to see why GH actions is removing the files that are generated by the mdbook.

**Comment by markulf** [comment]
Added a change log to the linked branch: https://github.com/ZK-Garage/plonk/blob/master/CHANGELOG.md

Might want to merge the linked pull request without closing the issue to get that into master. Not urgent, needed for version 0.1.

**Comment by markulf** [comment]
> Where will documentation pags go? https://docs.rs/ark-plonk/ is currently broken. Note that crate names need to be globally unique to run `cargo publish`.
> 
> They will go to the name that appears on the `Cargo.toml`. Anyway this will happen once we publish.
> 
Currently, the name is plonk, which seems to be taken https://crates.io/crates/plonk.

**Comment by CPerezz** [comment]
I know @markulf no worries! :)

We will change it before releasing in crates.io

**Comment by markulf** [comment]
I fixed broken links in the generated docs for `docs/notes-intro.md`, There is still a link to Unbalanced permutation arguments, that points to `unbalanced_perm_args/index.html` that I could not resolve. This file might be only in some local repository?

I comfirmed with Amira and others that this folder is just outdated and that the content will be superseded by the plonk book.

**Comment by markulf** [comment]
I added an `examples` folder, which is nicely supported by `cargo`. We might want to reproduce for instance the example from the plonk book there. The current example taken from circuit.rs is already quite close.
