### ISSUE TITLE
Plonk Book / Implementation Documentation

### ISSUE THREAD

**Issue by davidnevadoc** [ZK-Garage/plonk#23]
Add an extensive documentation in the style of [Halo2 Book](https://zcash.github.io/halo2/index.html).
It should contain:

- Theoretical background and explanation of Plonk
- Details of the implementation including: description of the structures and traits, complexitites of the main operations, differences from the original protocol, etc.
- Examples of use

The purpose of the book should be to allow new developers to learn how to use this library in the easiest way possible.

**Comment by markulf** [comment]
Hope its good to link the pull requests. I understand that no pull request is likely to close the issue completely as the book will be a living document.

**Comment by mathcrypto** [comment]
> Hope its good to link the pull requests. I understand that no pull request is likely to close the issue completely as the book will be a living document.

Thank you @markulf for linking the book PRs in one place. Yes the book is a living document that changes constantly according to the new updates
