### ISSUE TITLE
Consolidate naming for arithmetic Composer gates

### ISSUE THREAD

**Issue by CPerezz** [ZK-Garage/plonk#46]
I see the naming convention as follows:
 - The methods that have a `_gate` sufix (`add_gate`, `mul_gate`...) do not compute values, they receive as input the relevant wire values and selectors of the gate and check that the equation holds.
The methods that do not have the  `_gate` sufix (`add`, `mul`...) compute the output value `w_o` and always generate a satisfied constraint.
 - The methods with  `big_` prefix receive a 4th wire, those without the prefix don´t.

I think `big_arith` and `big_arith_gate` fit in the same family as `poly_gate` so we should choose a common name for all of them: `poly` or `arith`.

_Originally posted by @davidnevadoc in https://github.com/rust-zkp/ark-plonk/pull/43#discussion_r758801320_

**Comment by CPerezz** [comment]
We could extend this to all of the arithmetic gates of the crate and make a "standard" that makes it easier to understand how they work and how to use them aside from documentation.

**Comment by CPerezz** [comment]
I have a design proposal for this.

Instead of having all of the variants/naming conventions etc... what about the following:

We use a builder pattern and do the following:

```rust
let var_one = unimplemented!();
let output = composer.arithmetic_gate()
// Assigns `w_l`, `w_r`, `w_o` (if None, the gate computes it)
// Needs to be called  always but we're not in a macro to enforce it. 
// I still need to figure this out.
.witness(var_one, var_one, Some(var_one))
// Assigns `q_m`. If not called, `q_m = 0`
.mul(E::Fr::one())
// Assigns `q_l` & `q_r`. If not called,  `q_l = 0` & `q_r = 0`
.add(E::Fr::one(), E::Fr::one())
// Assigns `q_4` and `w_4` enabling fan in 3. (If not called, simply use fan in 2).
.fan_in_3(E::Fr::one(), var_one)
// Assigns `q_o`. If not called, `q_o = -1`
.out(-E::Fr::zero())
// Assigns `pi`. If not called, `pi = 0`
.pi(E::Fr::one());
```


This eliminates the need of needing `arithmetic` naming conventions and lots and lots of code. And instead a single function with a builder pattern allows to construct all of the possible gates will all of the combinations.

Any feedback is appreciated @davidnevadoc @LukePearson1 @bhgomes

**Comment by bhgomes** [comment]
Yeah, this sounds like a good idea. Probably want to declare upfront the fan-in, at the first call, not at the end, and you just have a builder for fan-in-2 and fan-in-3 depending on the selected one, since it's probably not a good idea to spread the witness and wire-selector information all up and down the function call.

You might also need a `finish` method since you'll have a type-level branch at `add`, but maybe not.

**Comment by mathcrypto** [comment]
This method isn't defined ```.const_sel```  in the previous definition you gave @CPerezz but it's used https://github.com/rust-zkp/ark-plonk/blob/7221a5d00aec5ab1c6edc3f9d107135d5e763758/src/constraint_system/arithmetic.rs#L265

**Comment by mathcrypto** [comment]
> This method isn't defined `.const_sel` in the previous definition you gave @CPerezz but it's used
> 
> https://github.com/rust-zkp/ark-plonk/blob/7221a5d00aec5ab1c6edc3f9d107135d5e763758/src/constraint_system/arithmetic.rs#L265

Oh just saw that it is in issue #59

**Comment by CPerezz** [comment]
> > This method isn't defined `.const_sel` in the previous definition you gave @CPerezz but it's used
> > https://github.com/rust-zkp/ark-plonk/blob/7221a5d00aec5ab1c6edc3f9d107135d5e763758/src/constraint_system/arithmetic.rs#L265
> 
> Oh just saw that it is in issue #59

It's for `q_c` basically. If there's a better naming, happy to get suggestions! :)

**Comment by bhgomes** [comment]
How about just `constant`? Not in favor of the `sel` suffix.
