### ISSUE TITLE
Improve `linearisation_poly` code 

### ISSUE THREAD

**Issue by davidnevadoc** [ZK-Garage/plonk#48]
There are some changes that could be made in order to improve the code of `linearisation_poly.rs` in terms of readability:
 - [ ] **Clearer variable names**: Have more descriptive names instead of potentially ambiguous or confusing names (`a`, `b`, `c`, `f_1`, etc.)
 - [ ] **Descriptive function names**: Try to reflect more accurately the purpose of the functions in its names
 - [ ] **Code comments**:  Add comments detailing which polynomials/ equations are being constructed and other clarifications when necessary

**Comment by bhgomes** [comment]
This is addressed in #45.

**Comment by davidnevadoc** [comment]
You are right!
I will add the changes I had in mind in the PR and will close this issue when it is merged.

**Comment by bhgomes** [comment]
~~I have a push that I'm waiting on since I lost push permissions, then you can see if my fixes addressed this issue.~~ I just moved the PR instead.
