### ISSUE TITLE
Fix broken doc link 

### ISSUE THREAD

**Issue by LukePearson1** [ZK-Garage/plonk#96]
The broken link is coming from the plonk-book. We need investigation into why it won't work. 

At the moment it is a blocker so we will ignore the `infra-link` on the PR's

cc: @CPerezz @mathcrypto @markulf

**Comment by CPerezz** [comment]
Which link are you referring to exactly? The one where the book has to be uploaded?

**Comment by markulf** [comment]
I noticed a broken Makefile that still refers to `docs/katex-header.html` and makes `make doc` fail.

Is this the same issue?

**Comment by markulf** [comment]
@CPerezz @LukePearson1 I will also fix the broken conflict in the README if that's ok:

Around **Examples**.

**Comment by markulf** [comment]
`CI checks / Intra-doc links (pull_request)` still fails.

```
Documenting plonk v0.8.2 (/home/runner/work/plonk/plonk)
thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:929:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic
Error: internal compiler error: unexpected panic
error: Unrecognized option: 'crate-version'
Error: Unrecognized option: 'crate-version'
error: could not document `plonk`
Error: could not document `plonk`
Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name plonk src/lib.rs -o /home/runner/work/plonk/plonk/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=ef6029efed173aea -L dependency=/home/runner/work/plonk/plonk/target/debug/deps --extern plonk_core=/home/runner/work/plonk/plonk/target/debug/deps/libplonk_core-4b8a6fd339527d4c.rmeta --extern plonk_hashing=/home/runner/work/plonk/plonk/target/debug/deps/libplonk_hashing-0c96a82c1e7093d4.rmeta --crate-version 0.8.2` (exit status: 1)
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```

Is this related to this issue? https://github.com/rust-lang/docs.rs/issues/1632

After running `rustup update`, I can now also reproduce this locally.

**Comment by markulf** [comment]
Just do document the outcome. I this was fixed by @davidnevadoc by pinning rustup and thus rustdoc to a slightly older version. I suppose this means that we need to take care that it doesn't get too old (and too painful to be uptodate).
